/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package log;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author S.NARESH
 */
public class Student_display extends javax.swing.JFrame {
    dbms db;
    /**
     * Creates new form Student_display
     */
    public Student_display() {
        db= new dbms();
        db.connect();
        
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.jpg")));

    }
    
    public void getStudentId(String studId){
        jLabel21.setText(studId);
        db.sid=studId;
        db.getStudent();
        jLabel22.setText(db.sname);
        jLabel23.setText(db.sgen);
        jLabel24.setText(db.sdob);
        jLabel25.setText(db.sphone);
        jLabel26.setText(db.sage);
        jLabel27.setText(db.semail);
        jLabel28.setText(db.sadd);
        
        
        try {
            
            DefaultTableModel mod2 = (DefaultTableModel)jTable1.getModel();
            String qur = "SELECT * FROM ATTENDENCE WHERE Reg_id='"+db.sid+"';";
            db.st.execute(qur);
            db.r=db.st.getResultSet();
            while(db.r.next()){
                db.sid=db.r.getString("Reg_id");
                db.month=db.r.getString("month");
                db.year=db.r.getInt("year");
                db.attend_per=db.r.getFloat("per");
                mod2.addRow(new Object[]{db.sid,db.month,db.year,db.attend_per});
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        
        
        if(jComboBox1.getSelectedItem().equals("UT 1")){
            try {
            String qur = "SELECT * FROM UT1 WHERE Reg_id='"+db.sid+"';";
            db.st.execute(qur);
            db.r=db.st.getResultSet();
            while(db.r.next()){
                db.os=db.r.getInt("os");
                db.dbms=db.r.getInt("dbms");
                db.se=db.r.getInt("se");
                db.lt=db.r.getInt("lt");
                db.cn=db.r.getInt("cn");
                db.tot=db.r.getInt("tot");
                db.per=db.r.getInt("per");
                DefaultTableModel mod = (DefaultTableModel)jTable2.getModel();
                mod.setRowCount(0);
                mod.addRow(new Object[]{db.sid,db.os,db.dbms,db.se,db.lt,db.cn,db.tot,db.per});
            }
            } catch (Exception e) {
            System.out.println(e);
            }
        }
        else if(jComboBox1.getSelectedItem().equals("UT 2")){
            try {
            String qur = "SELECT * FROM UT2 WHERE Reg_id='"+db.sid+"';";
            db.st.execute(qur);
            db.r=db.st.getResultSet();
            while(db.r.next()){
                db.os=db.r.getInt("os");
                db.dbms=db.r.getInt("dbms");
                db.se=db.r.getInt("se");
                db.lt=db.r.getInt("lt");
                db.cn=db.r.getInt("cn");
                db.tot=db.r.getInt("tot");
                db.per=db.r.getInt("per");
                DefaultTableModel mod = (DefaultTableModel)jTable2.getModel();
                mod.setRowCount(0);
                mod.addRow(new Object[]{db.sid,db.os,db.dbms,db.se,db.lt,db.cn,db.tot,db.per});
            }
            } catch (Exception e) {
            System.out.println(e);
            }
        }
        else if(jComboBox1.getSelectedItem().equals("UT 3")){
            try {
            String qur = "SELECT * FROM UT3 WHERE Reg_id='"+db.sid+"';";
            db.st.execute(qur);
            db.r=db.st.getResultSet();
            while(db.r.next()){
                db.os=db.r.getInt("os");
                db.dbms=db.r.getInt("dbms");
                db.se=db.r.getInt("se");
                db.lt=db.r.getInt("lt");
                db.cn=db.r.getInt("cn");
                db.tot=db.r.getInt("tot");
                db.per=db.r.getInt("per");
                DefaultTableModel mod = (DefaultTableModel)jTable2.getModel();
                mod.setRowCount(0);
                mod.addRow(new Object[]{db.sid,db.os,db.dbms,db.se,db.lt,db.cn,db.tot,db.per});
            }
            } catch (Exception e) {
            System.out.println(e);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student information System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(208, 243, 252));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("   ATTENDANCE");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 170, 50));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("PRINT");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 80, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log/previous.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 560, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("REG NO. :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 98, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText("ADDRESS :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 98, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("E-MAIL :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 98, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setText("AGE:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 98, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText("PHONE :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 98, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel18.setText("DOB :");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 98, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText("GENDER :");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 98, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel20.setText("NAME :");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 98, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setText("STUDENT INFORMATION SYSTEM");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student reg_id", "Operating System", "Database Management System", "Software Engineering", "Language Translator", "Computer Networks", "Total", "Percentage"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 770, 60));

        jLabel12.setBackground(new java.awt.Color(208, 243, 252));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("   STUDENT RESULT");
        jLabel12.setBorder(new javax.swing.border.MatteBorder(null));
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel12.setOpaque(true);
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 210, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Reg_ID", "Month", "Year", "Percentage"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 640, 120));

        jLabel21.setText("jLabel21");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 90, 20));

        jLabel22.setText("jLabel22");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 110, 20));

        jLabel23.setText("jLabel23");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 80, 20));

        jLabel24.setText("jLabel24");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 90, 20));

        jLabel25.setText("jLabel25");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 100, 20));

        jLabel26.setText("jLabel26");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 90, 20));

        jLabel27.setText("jLabel27");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 130, 20));

        jLabel28.setText("jLabel28");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 130, 30));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UT 1", "UT 2", "UT 3" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 860, 630));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log/projectbg.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1100, 700));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        login ob = new login();
        ob.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().equals("UT 1")){
            try {
            String qur = "SELECT * FROM UT1 WHERE Reg_id='"+db.sid+"';";
            db.st.execute(qur);
            db.r=db.st.getResultSet();
            while(db.r.next()){
                db.os=db.r.getInt("os");
                db.dbms=db.r.getInt("dbms");
                db.se=db.r.getInt("se");
                db.lt=db.r.getInt("lt");
                db.cn=db.r.getInt("cn");
                db.tot=db.r.getInt("tot");
                db.per=db.r.getInt("per");
                DefaultTableModel mod = (DefaultTableModel)jTable2.getModel();
                mod.setRowCount(0);
                mod.addRow(new Object[]{db.sid,db.os,db.dbms,db.se,db.lt,db.cn,db.tot,db.per});
            }
            } catch (Exception e) {
            System.out.println(e);
            }
        }
        else if(jComboBox1.getSelectedItem().equals("UT 2")){
            try {
            String qur = "SELECT * FROM UT2 WHERE Reg_id='"+db.sid+"';";
            db.st.execute(qur);
            db.r=db.st.getResultSet();
            while(db.r.next()){
                db.os=db.r.getInt("os");
                db.dbms=db.r.getInt("dbms");
                db.se=db.r.getInt("se");
                db.lt=db.r.getInt("lt");
                db.cn=db.r.getInt("cn");
                db.tot=db.r.getInt("tot");
                db.per=db.r.getInt("per");
                DefaultTableModel mod = (DefaultTableModel)jTable2.getModel();
                mod.setRowCount(0);
                mod.addRow(new Object[]{db.sid,db.os,db.dbms,db.se,db.lt,db.cn,db.tot,db.per});
            }
            } catch (Exception e) {
            System.out.println(e);
            }
        }
        else if(jComboBox1.getSelectedItem().equals("UT 3")){
            try {
            String qur = "SELECT * FROM UT3 WHERE Reg_id='"+db.sid+"';";
            db.st.execute(qur);
            db.r=db.st.getResultSet();
            while(db.r.next()){
                db.os=db.r.getInt("os");
                db.dbms=db.r.getInt("dbms");
                db.se=db.r.getInt("se");
                db.lt=db.r.getInt("lt");
                db.cn=db.r.getInt("cn");
                db.tot=db.r.getInt("tot");
                db.per=db.r.getInt("per");
                DefaultTableModel mod = (DefaultTableModel)jTable2.getModel();
                
                mod.setRowCount(0);
                mod.addRow(new Object[]{db.sid,db.os,db.dbms,db.se,db.lt,db.cn,db.tot,db.per});
            }
            } catch (Exception e) {
            System.out.println(e);
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PrinterJob pj = PrinterJob.getPrinterJob();
        pj.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if(pageIndex>0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D gra = (Graphics2D)graphics;
                gra.translate(pageFormat.getImageableX()*2, pageFormat.getImageableY()*2);
                gra.scale(0.5, 0.5);
                jPanel1.paint(gra);
                return Printable.PAGE_EXISTS;
            }
        });
        boolean ret=pj.printDialog();
        if(ret){
            try{
                pj.print();
            }catch(PrinterException e){
                JOptionPane.showMessageDialog(null,e,"Print Error",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
